name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # Install dependencies
      - name: install
        run: npm install

      # Generate types after installing dependencies
      - name: postinstall
        run: npm run postinstall

      - name: Sync Status
        run: git diff --exit-code

      - name: Build
        run: npm run build